name: Chisel-test-with-chisel3-tools

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docket pull and run
        run: |
          docker pull ucbbar/chisel3-tools
          docker run ucbbar/chisel3-tools
      - name: Check verilator
        run: |
          export PATH="/opt/verilator/verilator_4_016/bin:/opt/yosys/bin:$PATH"
          /opt/verilator/verilator_4_016/bin/verilator --version
      - name: Run test
        run:
          sbt "test"
