name: Verilator-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Display CPU info.
        run:
          cat /proc/cpuinfo
      - name: Build verilator
        run: |
          cat /proc/cpuinfo
          sudo apt install flex bison
          wget https://www.veripool.org/ftp/verilator-4.018.tgz
          tar xf verilator-4.018.tgz
          cd verilator-4.018
          ./configure
          make -j 3
          sudo make install
          verilator --version