name: Chisel-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependancy
        run: |
          sudo apt install flex bison gpg
      - name: Build verilator
        run: |
          wget https://www.veripool.org/ftp/verilator-4.018.tgz
          tar xf verilator-4.018.tgz
          cd verilator-4.018
          ./configure
          make -j 2
          sudo make install
          verilator --version
      - name: Install sbt
        run: |
          echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
          sudo apt update
          sudo apt install sbt
      - name: Run test
        run:
          sbt "test"
