name: git-clone

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Extract riscv-tests
        run: |
          git clone https://github.com/diningyo/misc-data.git
          tar Jxf misc-data/isa.tar.xz
          ls -l misc-data